name: Update Bot

on:
  push:
    branches:
      - main

jobs:
  stablish_connection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

  git_pull:
    needs: stablish_connection
    runs-on: ubuntu-latest
    steps:
      - name: git pull latest changes
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home/${{ secrets.SSH_USER }}/Server && git pull && npm install"

  update_bot:
    needs: git_pull
    runs-on: ubuntu-latest
    steps:
      - name: Check PM2 Status
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "npm restart &&npx pm2 ls"