name: Update Bot

on:
  push:
    branches:
      - main

jobs:
  check-pm2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Check PM2 Status
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "pm2 ls" &&
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home/nassay/Server && git pull && npm install && pm2 restart 0"